[package]
name = "kash-merkle"
description = "Kash merkle tree library"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
kash-hashes.workspace = true
