[package]
name = "kash-wallet"
description = "Kash wallet"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[features]
legacy-rpc = ["kash-cli/legacy-rpc"]
default = []

[dependencies]
async-std.workspace = true
async-trait.workspace = true
kash-cli.workspace = true
tokio.workspace = true
workflow-log.workspace = true
workflow-terminal.workspace = true
