[package]
name = "kash-wrpc-wasm"
description = "Kash wRPC WASM client"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
kash-wrpc-client.workspace = true
