[application]
name = "kash-os"
version = "Cargo.toml::package.version"
title = "Kash OS"
organization = "Kash Contributors"

[description]
short = "Kash Desktop OS"
long = """
Kash Desktop OS
""""

[package]
root = ".."
# resources = "resources/setup"
# exclude = ["resources/setup"]
exclude = [{ glob = ["{src/*,target/*,test/*,resources/setup/*,*.lock,*.toml,.git*,build*}"] }]
output = "../setup"
use-app-nw = true
update-package-json = true
build = [{ WASM = { name = "kash", outdir = "app/wasm" }}]

[nwjs]
version = "0.77.0"
windows = "0.72.0"
ffmpeg = false

[macos-disk-image]
# window_caption_height = 60
# icon_size = 72
# window_position = [200,200]
# window_size = [485,330]
application_icon_position = [100,178]
system_applications_folder_position = [385,178]

[windows]
uuid = "9464f462-db23-4f78-a027-c864db698121"
group = "Kash"
# run_on_startup = "everyone"
run_after_setup = true

# [languages]
# languages = ["english"]

[firewall]
application = { direction = "in+out" }
rules = [
    { name = "Kashd", program = "bin\\kashd.exe", direction="in+out" }
]

[[action]]
stage = "build"
name = "building rusty kash daemon (bin/kashd)"
items = [
    { run = { cmd = "cargo build --release --bin kashd", cwd = ".." } },
    { copy = { file = "../target/release/kashd$EXE", to = "$TARGET/bin/" } },
]

[[action]]
stage = "build"
name = "building kash CPU miner (bin/kash-cpu-miner)"
items = [
    { run = { cmd = "cargo build --release", cwd = "../../kash-cpu-miner" } },
    { copy = { file = "../../kash-cpu-miner/target/release/kash-miner$EXE", to = "$TARGET/bin/kash-cpu-miner$EXE" } },
]
