[package]
name = "kash-wrpc-proxy"
description = "Kash wRPC to gRPC proxy"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
clap.workspace = true
kash-consensus-core.workspace = true
kash-grpc-client.workspace = true
kash-rpc-core.workspace = true
kash-rpc-macros.workspace = true
kash-wrpc-core.workspace = true
kash-wrpc-server.workspace = true
num_cpus.workspace = true
thiserror.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true

[package.metadata.emanate.build]
folder = "setup"
